In [1]:
import re

# split()
- It splits the string from the pattern that we pass.
- It returns a list.

In [5]:
# Syntax- re.split(pattern,string)

In [4]:
text='Hello1good5morning'

re.split('\d',text)

['Hello', 'good', 'morning']

# fullmatch()
- It matches the complete pattern in a string.

In [7]:
# Syntax-re.fullmatch(pattern,string)

In [8]:
username='Ashish@123'
pat=r'Ashish@123'

re.fullmatch(pat,username)

<re.Match object; span=(0, 10), match='Ashish@123'>

In [11]:
username='12431432sdgsefhtwuAshish@123'
pat=r'Ashish@123'

print(re.fullmatch(pat,username))

None


In [15]:
username='Ashish@123315235asdrwet'
pat=r'Ashish@123'

print(re.fullmatch(pat,username))

None


# compile()

- It is used to create a regex pattern.
- It returns a re.Pattern object.
- We can call any regex function on re.Pattern object.

In [16]:
text='This is Python class.'

pat='Python'

x=re.finditer(pat,text)
for i in x:
    print(i)

<re.Match object; span=(8, 14), match='Python'>


In [21]:
text='This is Python class.'

pat=re.compile('Python')
print(pat,type(pat))

re.compile('Python') <class 're.Pattern'>


In [22]:
print(pat.match(text))
print(pat.search(text))

None
<re.Match object; span=(8, 14), match='Python'>


In [25]:
for i in pat.finditer(text):
    print(i)

<re.Match object; span=(8, 14), match='Python'>


In [27]:
text='This is Python class. I am learning Python.'

re.findall('Python',text)

['Python', 'Python']

In [28]:
pat=re.compile('Python')

In [29]:
pat.findall(text)

['Python', 'Python']

# Numpy

- Numpy is a Python librray. We call it as Python librray because it supports Python syntax.
- Numpy stands for Numerical Python.
- Numpy is used to perform advanced numerical computations on large datasets.
- By using Numpy we can perform complex operations with less lines of code.
- Numpy provides a very useful data structure known as array.

# How to import Numpy

In [3]:
import numpy as np

In [2]:
print(dir())

['In', 'Out', '_', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i2', '_ih', '_ii', '_iii', '_oh', 'exit', 'get_ipython', 'np', 'quit']


In [3]:
np.array([1,2,3,45])

array([ 1,  2,  3, 45])

# Version

In [4]:
np.__version__

'1.21.5'

# How to install numpy

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# How to update numpy

In [1]:
# conda update numpy

# Array

- An array is the collection of homogenous (same type) elements.

# How to create an array

In [4]:
# np.array()

In [5]:
lst=[10,20,30,40,50,60]
arr=np.array(lst)
arr

array([10, 20, 30, 40, 50, 60])

In [6]:
type(arr)

numpy.ndarray

In [7]:
lst=(10,20,30,40,50,60)
arr=np.array(lst)
arr

array([10, 20, 30, 40, 50, 60])

# List vs array
- With arrays we can easily perform some operation rather than a list.
- Arrays are faster than list.

In [8]:
# Multiple each element of the following list by 5

lst=[10,20,30,40,50,60]
print(lst,type(lst))

[10, 20, 30, 40, 50, 60] <class 'list'>


In [10]:
print(lst*5)

[10, 20, 30, 40, 50, 60, 10, 20, 30, 40, 50, 60, 10, 20, 30, 40, 50, 60, 10, 20, 30, 40, 50, 60, 10, 20, 30, 40, 50, 60]


In [11]:
for i in range(len(lst)):
    lst[i]*=5 # lst[i]=lst[i]*5
print(lst)

[50, 100, 150, 200, 250, 300]


In [13]:
# Multiple each element of the following arr by 5

lst=[10,20,30,40,50,60]
arr=np.array(lst)
arr

array([10, 20, 30, 40, 50, 60])

In [14]:
arr*5

array([ 50, 100, 150, 200, 250, 300])

# Arrays are faster than list

In [19]:
import time

In [21]:
st=time.time()

lst=[i for i in range(1000000)]

for i in range(len(lst)):
    lst[i]=lst[i]*5
    
tt=time.time()-st
print(tt)

0.20740628242492676


In [25]:
st=time.time()
arr=np.arange(1000000)
arr=arr*5
# arr
tt=time.time()-st
print(tt)

0.004565000534057617


# Why arrays are faster than a list

- On list we have to use loop to perform some operation.
- Loop makes the process slow.
- Arrays use vectorised operations by using array broadcasting and this process is much faster than loop.

- A list is a collection of heterogenous elements.
- A list has to store a lot of information for each element seperately becasue each element behaves differently in a list.
- This is the reason that makes the process slow.
- An array is the collection of homogenous elements. It does not store extra information for each element seperately.

In [26]:
a=True
print(a,type(a))

True <class 'bool'>


In [27]:
print(dir(bool))

['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'as_integer_ratio', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']


In [31]:
lst=[10]

In [30]:
print(id(lst))

2084697282112


In [32]:
print(id(lst[0]))

2084616956496


In [33]:
print(dir(lst[0]))

['__abs__', '__add__', '__and__', '__bool__', '__ceil__', '__class__', '__delattr__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floor__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getnewargs__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__trunc__', '__xor__', 'as_integer_ratio', 'bit_length', 'conjugate', 'denominator', 'from_bytes', 'imag', 'numerator', 'real', 'to_bytes']


# Array upcasting
- When we pass heterogenous elements to an array then it converts them to one type and this process is known as array upcasting.

In [34]:
# int -> float -> complex -> string -> object

In [35]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [36]:
arr.dtype

dtype('int32')

In [37]:
arr=np.array([10,20.5,30,40,50])
arr

array([10. , 20.5, 30. , 40. , 50. ])

In [38]:
arr.dtype

dtype('float64')

In [39]:
arr=np.array([10,20+5j,30,40,50])
arr

array([10.+0.j, 20.+5.j, 30.+0.j, 40.+0.j, 50.+0.j])

In [40]:
arr.dtype

dtype('complex128')

In [41]:
arr=np.array([10.5,20,30+6j,40,50])
arr

array([10.5+0.j, 20. +0.j, 30. +6.j, 40. +0.j, 50. +0.j])

In [42]:
arr.dtype

dtype('complex128')

In [43]:
arr=np.array([10,20,30,40,'50'])
arr

array(['10', '20', '30', '40', '50'], dtype='<U11')

In [44]:
arr=np.array([10,20.5,30,40,'50'])
arr

array(['10', '20.5', '30', '40', '50'], dtype='<U32')

In [45]:
arr=np.array([10.5,20+4j,30,40,'50'])
arr

array(['10.5', '(20+4j)', '30', '40', '50'], dtype='<U64')

In [58]:
arr=np.array([10,[20,30],40,'50'],dtype='object')
print(arr)

[10 list([20, 30]) 40 '50']


In [51]:
arr.dtype

dtype('O')

In [56]:
arr=np.array([10,20,30,40,'50', True,None])
print(arr)
print(arr.dtype)

[10 20 30 40 '50' True None]
object


In [53]:
print([10,20,30,40])

[10, 20, 30, 40]


# Attributes on arrays

### dtype
- It returns the type of the elements an array contains.

In [65]:
arr=np.array([10,20,-30,40,50])
arr

array([ 10,  20, -30,  40,  50])

In [66]:
arr.dtype

dtype('int32')

In [63]:
arr=np.array([10.50,-20,30,40,50])
arr

array([ 10.5, -20. ,  30. ,  40. ,  50. ])

In [64]:
arr.dtype

dtype('float64')

### size
- It returns the number of elements an array contains.

In [67]:
arr

array([ 10,  20, -30,  40,  50])

In [73]:
print(arr.size)
print(len(arr))

5
5


### shape
- It returns a tuple.
- If the tuple has single element then it represents the number of elements.
- If the tuple has two elements then the first element represents the number of rows and the second element represents the number of columns.

In [74]:
arr

array([ 10,  20, -30,  40,  50])

In [76]:
arr.shape

(5,)

In [77]:
arr=np.array([[2,4,6],[8,2,4]])
arr

array([[2, 4, 6],
       [8, 2, 4]])

In [78]:
arr.shape

(2, 3)

### ndim
- It returns the dimension of the array.

In [79]:
arr=np.array([10,20,30,540,560])
arr

array([ 10,  20,  30, 540, 560])

In [80]:
arr.ndim

1

In [81]:
arr=np.array([[2,4,6],[8,2,4]])
arr

array([[2, 4, 6],
       [8, 2, 4]])

In [85]:
arr.ndim

2

In [83]:
# Methods vs attributes

In [93]:
class Shrikant:
    def __init__(self):
        self.name='Shrikant'
        self.age=25
        self.salary=55000
        
    def intro(self):
        return 'I am Shrikant'

In [94]:
s=Shrikant()

In [95]:
s.name

'Shrikant'

In [96]:
s.age

25

In [97]:
s.salary

55000

In [98]:
s.intro()

'I am Shrikant'

# Creating different types of arrays

# np.arange()

- It creates an array of numbers.

In [104]:
# Syntax- np.arange(start,stop,step)
# Stop value is excluded
# Step is 1 by default

In [101]:
# Create an array that has the numbers from 1 to 10

lst=[i for i in range(1,11)]
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [102]:
np.array(lst)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [107]:
# Create an array of even numbers from 2 to 20

x=np.arange(2,21,2)
x

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

# np.linspace()

- It is used to create an array of equally spaced values within a range of values.

In [108]:
# Syntax- np.linspace(start,stop,number of values)
# Start and stop both are inclusive

In [109]:
# Create an array of 5 equally space values between 1 and 3

np.linspace(1,3,5)

array([1. , 1.5, 2. , 2.5, 3. ])

In [110]:
np.linspace(1,3,50)

array([1.        , 1.04081633, 1.08163265, 1.12244898, 1.16326531,
       1.20408163, 1.24489796, 1.28571429, 1.32653061, 1.36734694,
       1.40816327, 1.44897959, 1.48979592, 1.53061224, 1.57142857,
       1.6122449 , 1.65306122, 1.69387755, 1.73469388, 1.7755102 ,
       1.81632653, 1.85714286, 1.89795918, 1.93877551, 1.97959184,
       2.02040816, 2.06122449, 2.10204082, 2.14285714, 2.18367347,
       2.2244898 , 2.26530612, 2.30612245, 2.34693878, 2.3877551 ,
       2.42857143, 2.46938776, 2.51020408, 2.55102041, 2.59183673,
       2.63265306, 2.67346939, 2.71428571, 2.75510204, 2.79591837,
       2.83673469, 2.87755102, 2.91836735, 2.95918367, 3.        ])

In [111]:
# Create an array of 15 equally space values between 15 and 30

np.linspace(15,30,15)

array([15.        , 16.07142857, 17.14285714, 18.21428571, 19.28571429,
       20.35714286, 21.42857143, 22.5       , 23.57142857, 24.64285714,
       25.71428571, 26.78571429, 27.85714286, 28.92857143, 30.        ])

# np.zeros()

- It returns an array of the given shape where all the elements in the array are 0.

In [112]:
# np.zeros((rows,cols))

In [114]:
# Create a 3*3 matrix that has all the elements as 0

z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
z.dtype

dtype('float64')

In [116]:
# Create a 3*3 matrix that has all the elements as 0

z=np.zeros((3,3),dtype=int)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [117]:
z.dtype

dtype('int32')

In [122]:
# Create a 5*7 matrix that has all the elements as 0

z=np.zeros((5,7),dtype=int)
z

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

# np.ones()

- It returns an array of the given shape where all the elements are 1's.

In [124]:
# np.ones((rows,cols))

In [126]:
# Create a 4*4 matrix where all the elements are 1.

x=np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [127]:
x.dtype

dtype('float64')

In [128]:
x=np.ones((4,4),dtype=int)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [129]:
x.dtype

dtype('int32')

In [130]:
x.size

16