In [1]:
import numpy as np

In [3]:
arr=np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

# Slicing of a 2-D array

In [4]:
# arr[row_slicing]
# arr[start:stop:step]

# arr[row_slicing,col_slicing]
# arr[start:stop:step,start:stop:step]

In [5]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [10]:
# Get the first two rows from the above array

arr[0:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
# Reverse the rows
arr[::-1]

array([[70, 80, 90],
       [40, 50, 60],
       [10, 20, 30]])

In [12]:
# Alternate rows
arr[::2]

array([[10, 20, 30],
       [70, 80, 90]])

In [13]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
# Fetch the first column

arr[::,0]

array([10, 40, 70])

In [27]:
arr[::,[0]]

array([[10],
       [40],
       [70]])

In [20]:
arr[::,0:1]

array([[10],
       [40],
       [70]])

In [21]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [23]:
# Fetch the first two columns

arr[::,0:2]

array([[10, 20],
       [40, 50],
       [70, 80]])

In [25]:
# Reverse the columns
arr[::,::-1]

array([[30, 20, 10],
       [60, 50, 40],
       [90, 80, 70]])

In [29]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [30]:
# Reverse the rows and the columns both

arr[::-1,::-1]

array([[90, 80, 70],
       [60, 50, 40],
       [30, 20, 10]])

In [31]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [33]:
arr[::,::-1]

array([[30, 20, 10],
       [60, 50, 40],
       [90, 80, 70]])

In [35]:
# Fetch the principle diagonal from right to left

In [34]:
np.diagonal(arr[::,::-1])

array([30, 50, 70])

In [37]:
# Fetch the principle diagonal from right to left in reverse order
# [70,50,30]

In [40]:
np.diagonal(arr[::,::-1])[::-1]

array([70, 50, 30])

In [41]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [43]:
# Fetch the last column

arr[::,[-1]]

array([[30],
       [60],
       [90]])

In [45]:
arr[::,-1:-2:-1]

array([[30],
       [60],
       [90]])

In [46]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [47]:
# [[10,20],
# [40,50]]

In [49]:
arr[0:2,0:2]

array([[10, 20],
       [40, 50]])

In [51]:
# [[40,60],
# [70,90]]

In [54]:
arr[1:3,::2]

array([[40, 60],
       [70, 90]])

In [55]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [56]:
# [[10,30],
# [70,90]]

In [58]:
arr[::2,::2]

array([[10, 30],
       [70, 90]])

In [64]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [65]:
# [60,40]

In [75]:
arr[1,::-2]

array([60, 40])

# Indexing and slicing of a 3-D array

# indexing

In [76]:
# arr[array_index]
# arr[array_index,row_index]
# arr[array_index,row_index,col_index]

In [84]:
arr=np.random.randint(10,100,60).reshape(3,4,5)

In [85]:
arr

array([[[73, 41, 23, 79, 42],
        [14, 23, 97, 88, 82],
        [21, 39, 49, 69, 19],
        [34, 53, 56, 68, 99]],

       [[69, 13, 67, 58, 75],
        [60, 65, 72, 24, 20],
        [32, 32, 46, 77, 31],
        [82, 45, 52, 64, 38]],

       [[23, 19, 15, 94, 43],
        [56, 93, 69, 52, 24],
        [98, 40, 85, 12, 28],
        [43, 26, 38, 29, 13]]])

In [83]:
arr.ndim

5

In [86]:
# Fetch the first array
arr[0]

array([[73, 41, 23, 79, 42],
       [14, 23, 97, 88, 82],
       [21, 39, 49, 69, 19],
       [34, 53, 56, 68, 99]])

In [91]:
arr[-3]

array([[73, 41, 23, 79, 42],
       [14, 23, 97, 88, 82],
       [21, 39, 49, 69, 19],
       [34, 53, 56, 68, 99]])

In [94]:
arr[-len(arr)]

array([[73, 41, 23, 79, 42],
       [14, 23, 97, 88, 82],
       [21, 39, 49, 69, 19],
       [34, 53, 56, 68, 99]])

In [88]:
# Get the last array
arr[2]

array([[23, 19, 15, 94, 43],
       [56, 93, 69, 52, 24],
       [98, 40, 85, 12, 28],
       [43, 26, 38, 29, 13]])

In [89]:
arr[-1]

array([[23, 19, 15, 94, 43],
       [56, 93, 69, 52, 24],
       [98, 40, 85, 12, 28],
       [43, 26, 38, 29, 13]])

In [96]:
arr[len(arr)-1]

array([[23, 19, 15, 94, 43],
       [56, 93, 69, 52, 24],
       [98, 40, 85, 12, 28],
       [43, 26, 38, 29, 13]])

In [97]:
arr

array([[[73, 41, 23, 79, 42],
        [14, 23, 97, 88, 82],
        [21, 39, 49, 69, 19],
        [34, 53, 56, 68, 99]],

       [[69, 13, 67, 58, 75],
        [60, 65, 72, 24, 20],
        [32, 32, 46, 77, 31],
        [82, 45, 52, 64, 38]],

       [[23, 19, 15, 94, 43],
        [56, 93, 69, 52, 24],
        [98, 40, 85, 12, 28],
        [43, 26, 38, 29, 13]]])

In [98]:
# Fetch the first row from the first array

In [100]:
arr[0,0]

array([73, 41, 23, 79, 42])

In [101]:
# Fetch the last row from the second array

In [106]:
arr[1,-1]

array([82, 45, 52, 64, 38])

In [107]:
# Fetch  from the third array

In [113]:
arr[-1,1,3]

52

In [114]:
# Fetch 46 from the second array

In [117]:
arr[1,2,2]

46

In [126]:
arr[1][0][-1]

75

In [133]:
arr.shape

(3, 4, 5)

# Slicing

In [134]:
# arr[array_slicing]
# arr[start:stop:step]

# arr[array_slicing,row_slicing]
# arr[start:stop:step,start:stop:step]

# arr[array_slicing,row_slicing,col_slicing]
# arr[start:stop:step,start:stop:step,start:stop:step]

In [135]:
arr

array([[[73, 41, 23, 79, 42],
        [14, 23, 97, 88, 82],
        [21, 39, 49, 69, 19],
        [34, 53, 56, 68, 99]],

       [[69, 13, 67, 58, 75],
        [60, 65, 72, 24, 20],
        [32, 32, 46, 77, 31],
        [82, 45, 52, 64, 38]],

       [[23, 19, 15, 94, 43],
        [56, 93, 69, 52, 24],
        [98, 40, 85, 12, 28],
        [43, 26, 38, 29, 13]]])

In [136]:
# Fetch the first two arrays

In [137]:
arr[0:2]

array([[[73, 41, 23, 79, 42],
        [14, 23, 97, 88, 82],
        [21, 39, 49, 69, 19],
        [34, 53, 56, 68, 99]],

       [[69, 13, 67, 58, 75],
        [60, 65, 72, 24, 20],
        [32, 32, 46, 77, 31],
        [82, 45, 52, 64, 38]]])

In [138]:
# Reverse the arrays

In [139]:
arr[::-1]

array([[[23, 19, 15, 94, 43],
        [56, 93, 69, 52, 24],
        [98, 40, 85, 12, 28],
        [43, 26, 38, 29, 13]],

       [[69, 13, 67, 58, 75],
        [60, 65, 72, 24, 20],
        [32, 32, 46, 77, 31],
        [82, 45, 52, 64, 38]],

       [[73, 41, 23, 79, 42],
        [14, 23, 97, 88, 82],
        [21, 39, 49, 69, 19],
        [34, 53, 56, 68, 99]]])

In [140]:
# Alternate arrays

In [141]:
arr[::2]

array([[[73, 41, 23, 79, 42],
        [14, 23, 97, 88, 82],
        [21, 39, 49, 69, 19],
        [34, 53, 56, 68, 99]],

       [[23, 19, 15, 94, 43],
        [56, 93, 69, 52, 24],
        [98, 40, 85, 12, 28],
        [43, 26, 38, 29, 13]]])

In [142]:
arr

array([[[73, 41, 23, 79, 42],
        [14, 23, 97, 88, 82],
        [21, 39, 49, 69, 19],
        [34, 53, 56, 68, 99]],

       [[69, 13, 67, 58, 75],
        [60, 65, 72, 24, 20],
        [32, 32, 46, 77, 31],
        [82, 45, 52, 64, 38]],

       [[23, 19, 15, 94, 43],
        [56, 93, 69, 52, 24],
        [98, 40, 85, 12, 28],
        [43, 26, 38, 29, 13]]])

In [143]:
# Fetch the first two rows from the first array

In [146]:
arr[0,0:2]

array([[73, 41, 23, 79, 42],
       [14, 23, 97, 88, 82]])

In [147]:
# First row from all the arrays

In [150]:
arr[::,[0]]

array([[[73, 41, 23, 79, 42]],

       [[69, 13, 67, 58, 75]],

       [[23, 19, 15, 94, 43]]])

In [151]:
# First column from all the arrays

In [155]:
arr[::,::,[0]]

array([[[73],
        [14],
        [21],
        [34]],

       [[69],
        [60],
        [32],
        [82]],

       [[23],
        [56],
        [98],
        [43]]])

In [157]:
arr

array([[[73, 41, 23, 79, 42],
        [14, 23, 97, 88, 82],
        [21, 39, 49, 69, 19],
        [34, 53, 56, 68, 99]],

       [[69, 13, 67, 58, 75],
        [60, 65, 72, 24, 20],
        [32, 32, 46, 77, 31],
        [82, 45, 52, 64, 38]],

       [[23, 19, 15, 94, 43],
        [56, 93, 69, 52, 24],
        [98, 40, 85, 12, 28],
        [43, 26, 38, 29, 13]]])

In [156]:
# Get the last two columns from the first two arrays

In [161]:
arr[0:2,::,3:]

array([[[79, 42],
        [88, 82],
        [69, 19],
        [68, 99]],

       [[58, 75],
        [24, 20],
        [77, 31],
        [64, 38]]])

In [162]:
arr

array([[[73, 41, 23, 79, 42],
        [14, 23, 97, 88, 82],
        [21, 39, 49, 69, 19],
        [34, 53, 56, 68, 99]],

       [[69, 13, 67, 58, 75],
        [60, 65, 72, 24, 20],
        [32, 32, 46, 77, 31],
        [82, 45, 52, 64, 38]],

       [[23, 19, 15, 94, 43],
        [56, 93, 69, 52, 24],
        [98, 40, 85, 12, 28],
        [43, 26, 38, 29, 13]]])

In [167]:
# [[[23,82],
#  [53,99]],
 
#  [[65,20],
#  [45,38]],
 
#  [[93,24],
#  [26,13]]]

In [166]:
arr[::,1::2,1::3]

array([[[23, 82],
        [53, 99]],

       [[65, 20],
        [45, 38]],

       [[93, 24],
        [26, 13]]])

In [168]:
arr

array([[[73, 41, 23, 79, 42],
        [14, 23, 97, 88, 82],
        [21, 39, 49, 69, 19],
        [34, 53, 56, 68, 99]],

       [[69, 13, 67, 58, 75],
        [60, 65, 72, 24, 20],
        [32, 32, 46, 77, 31],
        [82, 45, 52, 64, 38]],

       [[23, 19, 15, 94, 43],
        [56, 93, 69, 52, 24],
        [98, 40, 85, 12, 28],
        [43, 26, 38, 29, 13]]])

In [177]:
arr[0:1,::,0:1]

array([[[73],
        [14],
        [21],
        [34]]])

# Array of random values

- In numpy we have random module that is used to create arrays of random values.

# random.random()

- It generates specified number of random values.
- The random value is always between 0 and 1

In [178]:
# np.random.random(number of values)

In [182]:
np.random.random(20)

array([0.96026713, 0.05212885, 0.83046037, 0.05885026, 0.03486997,
       0.55553045, 0.79845162, 0.01514959, 0.67670289, 0.88371862,
       0.10677787, 0.58418785, 0.09869156, 0.19667819, 0.42049122,
       0.17328013, 0.70216845, 0.99089232, 0.00568414, 0.67512048])

In [183]:
# Create a 3*3 matrix of random values

In [186]:
np.random.random(9).reshape(3,3)

array([[0.79136126, 0.29307826, 0.69657399],
       [0.41057176, 0.20004087, 0.67834765],
       [0.26758662, 0.96842662, 0.96807001]])

# random.rand()

- It returns an array of the random values of the given shape.
- The random values are between 0 and 1

In [189]:
# np.random.rand(rows,cols)

In [187]:
# Create a 3*3 matrix of random values

In [188]:
np.random.rand(3,3)

array([[0.71001035, 0.49927675, 0.20732186],
       [0.97164288, 0.6579455 , 0.12465609],
       [0.87146622, 0.49259565, 0.36266828]])

In [190]:
# Create a 5*6 matrix of random values

In [202]:
print(np.random.random(30).reshape(5,6))

[[0.57480593 0.08142984 0.21788712 0.1770129  0.1963806  0.28144167]
 [0.03125799 0.15343245 0.37122609 0.21563423 0.65621778 0.74816415]
 [0.80941844 0.39527775 0.93023321 0.62811314 0.2248006  0.69223621]
 [0.52541537 0.76646524 0.26576658 0.489979   0.2678287  0.53788803]
 [0.13186133 0.0091547  0.83687093 0.10398259 0.89107908 0.76587718]]


In [205]:
print(np.random.rand(5,6))

[[0.65599368 0.98870009 0.52704899 0.69873379 0.24922587 0.73410323]
 [0.00694001 0.08471945 0.35032749 0.87524608 0.35284468 0.39080793]
 [0.08352907 0.6396506  0.99374416 0.32908675 0.68310465 0.24611154]
 [0.15353878 0.65039867 0.32401101 0.26207097 0.41061662 0.14697748]
 [0.39407572 0.51393446 0.37805532 0.46181128 0.38030167 0.80479014]]


In [207]:
r=np.random.rand(5,6)
print(r)

[[0.40567909 0.00835369 0.18470733 0.05661304 0.57680471 0.7837248 ]
 [0.08701426 0.58793775 0.60697103 0.29494202 0.69656167 0.51176833]
 [0.12587971 0.46787351 0.18575603 0.27754715 0.59833747 0.76576756]
 [0.23326132 0.93578341 0.70446849 0.50471349 0.20177347 0.91166469]
 [0.77488056 0.21845422 0.39010963 0.51967215 0.19232255 0.82426271]]


# random.randint()

- It returns an array of random integer values between a range.

In [209]:
# np.random.randint(start,stop,number of values)
# Stop is excluded

In [210]:
# Generate 10 random integer numbers between 10 and 50

In [218]:
np.random.randint(10,51,10)

array([24, 41, 33, 29, 47, 38, 49, 28, 27, 43])

In [219]:
# Generate 20 random integer numbers between 1 and 5

In [246]:
np.random.randint(1,6,20)

array([3, 2, 3, 4, 3, 3, 2, 2, 2, 5, 3, 4, 1, 5, 5, 1, 5, 5, 1, 1])

In [226]:
# Create a 5*4 matrix of random integer numbers between 10 and 100

In [243]:
x=np.random.randint(10,101,20).reshape(5,4)
x

array([[47, 20, 60, 58],
       [82, 28, 51, 72],
       [98, 92, 45, 58],
       [64, 48, 93, 46],
       [16, 23, 58, 62]])

# random.seed(random state)

- It is used to set the random state.
- Random state is an int number in the range 0 to 2**32-1

In [299]:
np.random.seed(36)
arr=np.random.randint(10,100,5)
arr

array([15, 40, 50, 43, 54])

In [297]:
np.random.seed(550)
arr=np.random.randint(10,100,20)
arr

array([47, 76, 50, 20, 12, 12, 31, 16, 20, 42, 71, 57, 29, 99, 66, 25, 38,
       56, 16, 46])

In [275]:
# array([47, 76, 50, 20, 12, 12, 31, 16, 20, 42])

In [293]:
np.random.seed(5)

In [303]:
np.random.randint(10,100,5)

array([40, 55, 31, 23, 47])

In [285]:
# array([88, 71, 26, 83, 18])

In [304]:
2**32-1

4294967295

In [310]:
np.random.seed(4294967295)
np.random.random(5)

array([0.09763203, 0.91238285, 0.7890353 , 0.7800036 , 0.01793967])

In [336]:
np.random.seed(5)
x=np.random.randint(10,100,5)
x

array([88, 71, 26, 83, 18])

In [334]:
np.random.seed(9)
x=np.random.randint(10,100,5)
x

array([64, 66, 32, 75, 32])

In [370]:
np.random.seed(9)
print(np.random.randint(100,1000,5))
print(np.random.randint(1,5,5))

[482 448 738 601 156]
[4 3 2 2 3]


In [373]:
np.random.randint(100,1000,5)

array([996, 338, 287, 572, 577])

In [375]:
# Pandas- 4 classes
# Matplotlib- 2 classes
# Seaborn- 1 classes

In [376]:
# Decorators
# Case studies